#!/usr/local/Python-3.7/bin/python
import pymysql
import sys
import cgi
import pandas as pd

import cgitb
cgitb.enable()

# print content-type
print("Content-type: text/html\n")

print("<html><head>")
print("<title>Upper Columbia River Site Database</title>")

print('''<style>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;

}

.topnav {
  overflow: hidden;
  background-color: #20b2aa;
}

.topnav a {
  float: left;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #8fbc8f ;
  color: white;
}

.topnav a.active {
  background-color: #00aaff;
  color: white;
}
body {margin:30;padding:30}

table, td, th {
  border: 1px solid black;
  text-align: center;
}

table {
  border-collapse: collapse;
}

.container {
  position: relative;
}

.container2 {
  position:absolute;
}

#right {
  float:right;
}

.center {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}

.imgbottom {
  position:absolute;
  top:-90px;
  left:-10px;
  width: 300px;
  padding: 10px;

}

.imgbottomright {
  position:absolute;
  top:-90px;
  left:-150;
  width:300px;
  padding: 10px;
}


</style>
</head>''')
print("</head>")
print("<body>")

print('''<h1 align="center"> Upper Columbia River Site Database </h1>''')

print('''
  <div class="container2">
  <div class="imgbottom">
        <div id="logo">
        <img src="/images/students_21/group_proj/group_G/logo.jpg" style="width:200px;height80px;">
  </div>
  </div>
  </div>
''')

print('''
 <div class="topnav">
  <a class="active" href="https://bioed.bu.edu/cgi-bin/students_21/group_proj/group_G/intro">Introduction</a>
  <a href="https://bioed.bu.edu/cgi-bin/students_21/group_proj/group_G/home">Home</a>
  <a href="https://bioed.bu.edu/cgi-bin/students_21/group_proj/group_G/upload">Upload</a>
  <a href="https://bioed.bu.edu/cgi-bin/students_21/group_proj/group_G/help">Help Page</a>
</div>
''')

print('''<h1 align ="center">Introduction</h1>''')
print("<body>")

print(""" 
<p style="text-align:center;"> Advised by Whitney Fraser, Lodestone Environmental Consulting LLC</p>
<p style="text-align:center;"> Developed by Allison Nau, Mae Rose Gott, Neha Gupta, and Giulia DiGiovanni</p>
<p style="text-align:center;"> This database was developed at Boston University, as part of BF768: Biological Database Analysis
Spring 2021, with Professor G. Benson</p>
""")


print('''<h1 align="center">Purpose of the UCRS Database</h1>''')
print("<body>")

print('''
<p style="margin-bottom:0;" align="center">
	The purpose of this database is to serve as a tool for multiple research agencies involved in the investigation of the Columbia River Site contamination. Our database intends to allow these agencies to upload, retrieve, and map scientific findings  
</p>
<p style="margin : 0; padding-top:0;" align="center">
	This will allow for centralization of all the studies conducted on the Columbia River Site contamination dating back to 1990. 
	This centralization provides researchers the resources to obtain and store data in a manageable format.  
</p>

<p style="margin : 0; padding-top:0;" align="center">
	This database intends to also serve as a communication tool with the public who utilize the Columbia River in their everyday lives. 
	Through the use of graphical imaging users will be able to locate and identify possible contamination sites. 
</p>

<p style="margin :0; padding-top:0;" align="center"> 
	
	The data within this site currently includes information regarding <b>only</b> sediment data.  
</p>

<p style="margin :0; padding-top:0;" align="center"> We hope users may find this database informative and convenient way of maintaining information. 
</p> 

<p align="center"> To begin navigating through the database click the button below or the Home button in the top left corner!</p>
''')


print("""
<div class="container" style="height:30px;">
<div class="center">
  <a href="https://bioed.bu.edu/cgi-bin/students_21/group_proj/group_G/home"><button>Search Database</button></a>
</div>
</div>
""")


print('''<h1 align="center" style="top:5px;"> For Help</h1>''')

print('''
<p align="center"> For information regarding how to navigate through this database please click below or see the Help button in the top left corner</p>
''')

print('''
<div class="container">
<div class="center">
	<a href="https://bioed.bu.edu/cgi-bin/students_21/group_proj/group_G/help"><button>Help Page</button></a>
</div>
</div>
''')

print('''
 <div class="container2">
 <div class="imgbottomright">
   <div id="right">
   <img src="https://logotyp.us/files413/bu.svg" style="width:200px;height:300px;">
 </div>
 </div>
 </div>
''')

print('''</body></html>''')
